# Generated by Django 4.0.5 on 2022-10-24 07:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('abstract', models.TextField()),
                ('publicationDate', models.DateField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
