# Generated by Django 4.0.5 on 2022-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
