# Generated by Django 4.0.5 on 2022-06-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marker',
            new_name='Publication',
        ),
    ]
