# Generated by Django 4.0.5 on 2022-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_doi_publication_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
