# Generated by Django 4.0.5 on 2022-12-23 08:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJSservers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_field', models.URLField()),
                ('harvest_interval_minutes', models.IntegerField(default=4320)),
                ('last_harvest', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=4096)),
                ('timeperiod_startdate', models.DateField(null=True)),
                ('timeperiod_enddate', models.DateField(null=True)),
                ('search_area', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('user_name', models.CharField(max_length=4096)),
            ],
            options={
                'verbose_name': 'subscription',
                'ordering': ['user_name'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='timeperiod_enddate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='publication',
            name='timeperiod_startdate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326, verbose_name='Publication geometry (Points, Lines, Polygons as GeoJSON)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publicationDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
