# Generated by Django 4.0.5 on 2022-12-23 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_ojsservers_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='creationDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='timeperiod_enddate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='timeperiod_startdate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
