# Generated by Django 4.0.5 on 2023-01-27 08:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_publication_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326, verbose_name='Publication geometry/ies'),
        ),
    ]
